### ISSUE TITLE
`EnsureListOfNumbers` doesn't assert properly

### ISSUE THREAD

**Issue by thomb** [syhpoon/xenvman#1]
If a parameter is defined as a list of numbers, `EnsureListOfNumbers` doesn't validate the input correctly.

Example definition 
```
type.EnsureListOfNumbers("ports", params.ports);
```

Example invocation
```
import_template("path/to/template/definition", {    
    "service":            "myService",     
    "ports":              [5000],     
});                                   
```

This will result in the `xenvman` server throwing the following error (full stack available upon request):

```
2019-02-19T15:08:17-05:00 [ERROR] at server.go:246: Error creating env: Error running template: ports: Expected array of strings but got []int64
```

**Comment by syhpoon** [comment]
Thanks, Thomas!
This issue should be fixed in [v2.1.2](https://github.com/syhpoon/xenvman/releases/tag/v2.1.2) minor release.
